-- V10 — SPRINT-12 (3/4): reconciliacion de caja al cierre de turno.
-- Entidades separadas (no se sobrecarga `shifts`): estos campos solo existen
-- cuando el turno se reconcilia, y los egresos son N por turno.

CREATE TABLE shift_expenses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    shift_id    BIGINT NOT NULL REFERENCES shifts(id),
    amount      NUMERIC(38,2) NOT NULL CHECK (amount > 0),
    reason      VARCHAR(255) NOT NULL,
    username    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE shift_reconciliations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL,
    shift_id       BIGINT NOT NULL UNIQUE REFERENCES shifts(id),
    opening_cash   NUMERIC(38,2) NOT NULL,
    declared_cash  NUMERIC(38,2) NOT NULL,
    expected_cash  NUMERIC(38,2) NOT NULL,
    difference     NUMERIC(38,2) NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);
