-- V1 — Baseline schema, generado desde las entidades JPA reales el 06-Sep-2026
-- (SPRINT-08B: adopción de Flyway, ver vault Proyecto Belopia SaaS / sprints/SPRINT-08B)
--
-- Generado con Hibernate ddl-auto=create contra una base vacía + pg_dump --schema-only,
-- para que el baseline refleje exactamente lo que las entidades actuales producen.
-- A partir de acá, todo cambio de schema es una migración V{n} nueva — nunca ddl-auto.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public.app_users (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    status character varying(10) NOT NULL,
    full_name character varying(255) NOT NULL,
    keycloak_id character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT app_users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories (
    active boolean NOT NULL,
    display_order integer,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    parent_id bigint,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255) NOT NULL
);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.closing_deposits (
    amount numeric(38,2) NOT NULL,
    closings_count integer,
    deposit_date date NOT NULL,
    period_end date NOT NULL,
    period_start date NOT NULL,
    id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    image_uri character varying(512),
    username character varying(255) NOT NULL,
    CONSTRAINT closing_deposits_closings_count_check CHECK ((closings_count >= 1))
);

ALTER TABLE public.closing_deposits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.closing_deposits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.gasto_admin (
    fecha date NOT NULL,
    monto numeric(10,2) NOT NULL,
    monto_danli numeric(10,2),
    monto_paraiso numeric(10,2),
    porcentaje_danli integer,
    porcentaje_paraiso integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(100) NOT NULL,
    descripcion character varying(255) NOT NULL
);

ALTER TABLE public.gasto_admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gasto_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.inventory_movements (
    quantity integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    source character varying(20),
    performed_by character varying(100),
    notes character varying(255),
    reason character varying(255),
    type character varying(255) NOT NULL,
    username character varying(255)
);

ALTER TABLE public.inventory_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.inventory_stock (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.inventory_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.products (
    active boolean NOT NULL,
    min_stock integer NOT NULL,
    price numeric(38,2) NOT NULL,
    category_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255) NOT NULL,
    sku character varying(255),
    type character varying(255) NOT NULL
);

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.salary_payments (
    amount numeric(38,2) NOT NULL,
    salary_date date NOT NULL,
    id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    description character varying(200) NOT NULL,
    image_uri character varying(512),
    username character varying(255) NOT NULL
);

ALTER TABLE public.salary_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salary_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sale_items (
    quantity integer NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    unit_price_snapshot numeric(12,2) NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL,
    product_name_snapshot character varying(255) NOT NULL,
    CONSTRAINT sale_items_quantity_check CHECK ((quantity >= 1))
);

ALTER TABLE public.sale_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sales (
    card_amount numeric(12,2),
    cash_amount numeric(12,2),
    isv numeric(12,2) NOT NULL,
    sale_date date NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    shift_id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    payment_method character varying(10),
    status character varying(10) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT sales_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CONFIRMED'::character varying])::text[])))
);

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shifts (
    closed_at timestamp(6) without time zone,
    id bigint NOT NULL,
    opened_at timestamp(6) without time zone,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    status character varying(10) NOT NULL,
    code character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT shifts_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);

ALTER TABLE public.shifts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shifts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.store (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    address character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);

ALTER TABLE public.store ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.supplier_payments (
    amount numeric(38,2) NOT NULL,
    payment_date date NOT NULL,
    id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    image_uri character varying(512),
    description character varying(255),
    supplier character varying(255),
    username character varying(255) NOT NULL
);

ALTER TABLE public.supplier_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.taxes (
    active boolean NOT NULL,
    rate numeric(5,2) NOT NULL,
    category_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    product_id bigint,
    tenant_id bigint NOT NULL,
    applies_to character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    name character varying(50) NOT NULL
);

ALTER TABLE public.taxes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taxes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tenant_config (
    currency character varying(3),
    tenant_id bigint NOT NULL,
    phone character varying(30),
    timezone character varying(50),
    company_name character varying(200),
    company_logo character varying(500),
    address text
);

CREATE TABLE public.tenants (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    plan character varying(20) NOT NULL,
    slug character varying(50) NOT NULL,
    name character varying(200) NOT NULL
);

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.transactions (
    amount numeric(38,2) NOT NULL,
    date date NOT NULL,
    gasto_admin_id bigint,
    id bigint NOT NULL,
    store_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    image_uri character varying(512),
    description character varying(255),
    type character varying(255) NOT NULL
);

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_keycloak_id_key UNIQUE (keycloak_id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_username_key UNIQUE (username);
ALTER TABLE ONLY public.categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.closing_deposits ADD CONSTRAINT closing_deposits_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.gasto_admin ADD CONSTRAINT gasto_admin_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_movements ADD CONSTRAINT inventory_movements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_stock ADD CONSTRAINT inventory_stock_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_stock ADD CONSTRAINT inventory_stock_product_id_store_id_key UNIQUE (product_id, store_id);
ALTER TABLE ONLY public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.salary_payments ADD CONSTRAINT salary_payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sale_items ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shifts ADD CONSTRAINT shifts_code_key UNIQUE (code);
ALTER TABLE ONLY public.shifts ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.store ADD CONSTRAINT store_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.supplier_payments ADD CONSTRAINT supplier_payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.taxes ADD CONSTRAINT taxes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_config ADD CONSTRAINT tenant_config_pkey PRIMARY KEY (tenant_id);
ALTER TABLE ONLY public.tenants ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenants ADD CONSTRAINT tenants_slug_key UNIQUE (slug);
ALTER TABLE ONLY public.transactions ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.inventory_movements ADD CONSTRAINT fk7lws1ve8g6b9itc054wj06uit FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE ONLY public.sale_items ADD CONSTRAINT fk7tcpbc5c5mpnm8fl2phl8ep7l FOREIGN KEY (sale_id) REFERENCES public.sales(id);
ALTER TABLE ONLY public.sale_items ADD CONSTRAINT fk8g0sjiqs7tg055o06p6wawu39 FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE ONLY public.inventory_stock ADD CONSTRAINT fk8lg1rxvcddib924nmunq6k4tu FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE ONLY public.closing_deposits ADD CONSTRAINT fkc8wcwqj2od4mtv3dftlqgnja1 FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.salary_payments ADD CONSTRAINT fkcyji6ddw8a6kfe2fb41seqfga FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.inventory_stock ADD CONSTRAINT fkdia6qiy5k9v30bbasnmxc75cf FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.transactions ADD CONSTRAINT fkeegbvswkokijaj85y6x263o8j FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT fkg9xcbnqpq1y7ajiocoikl9t2q FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.products ADD CONSTRAINT fkj6t0t0nb9wyi1fjyacp5643n9 FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.sales ADD CONSTRAINT fkkryy18fg74hqqnrstgd9mq428 FOREIGN KEY (shift_id) REFERENCES public.shifts(id);
ALTER TABLE ONLY public.products ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);
ALTER TABLE ONLY public.shifts ADD CONSTRAINT fkom4ycm7tdtjgnwn21sny6wsye FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.categories ADD CONSTRAINT fkpq1rrk85xcdwf8socc6prhkm3 FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.inventory_movements ADD CONSTRAINT fkrniie72i77er43pxuas83323v FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.categories ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);
ALTER TABLE ONLY public.supplier_payments ADD CONSTRAINT fksdq6r2d069b3trkeaujvu3wp0 FOREIGN KEY (store_id) REFERENCES public.store(id);
ALTER TABLE ONLY public.sales ADD CONSTRAINT fkt9e650iv592u855bwpbfcy459 FOREIGN KEY (store_id) REFERENCES public.store(id);
