-- V4 — SPRINT-14: Roles personalizables definidos por root.
-- Reemplaza el business_role libre (SPRINT-09) y el rol fijo Keycloak "admin".
CREATE TABLE roles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL REFERENCES tenants(id),
    name              VARCHAR(100) NOT NULL,
    level             INT NOT NULL CHECK (level > 0),
    can_manage_users  BOOLEAN NOT NULL DEFAULT FALSE,
    created_by        BIGINT REFERENCES app_users(id),
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

-- Sin tenant_id propio: el aislamiento se hereda de roles.tenant_id vía FK.
CREATE TABLE role_permissions (
    role_id    BIGINT      NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission VARCHAR(50) NOT NULL,
    PRIMARY KEY (role_id, permission)
);
