-- V7 — SPRINT-11: depositos bancarios. Un BankDeposit agrupa uno o mas
-- closing_deposits (cierres de caja) en un solo deposito fisico al banco.
-- tenant_id es una columna simple, nunca FK real a `tenants` (ver V4_1 --
-- esa tabla no esta poblada, el onboarding de tenants todavia no existe).
CREATE TABLE bank_deposits (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL,
    store_id         BIGINT NOT NULL REFERENCES store(id),
    deposit_date     DATE NOT NULL,
    declared_amount  NUMERIC(38,2) NOT NULL CHECK (declared_amount > 0),
    notes            TEXT,
    image_uri        VARCHAR(512),
    username         VARCHAR(255) NOT NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP
);

ALTER TABLE closing_deposits ADD COLUMN bank_deposit_id BIGINT NULL REFERENCES bank_deposits(id);
